/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package httpk

import httpk.server.Server
import httpk.util.consoleLog
import java.nio.file.Paths


fun main() {
    Runtime.getRuntime().addShutdownHook(Thread { consoleLog("server terminated.") })

    val server = Server(
        documentRoot = Paths.get("../sample").toAbsolutePath().normalize(),
        port = 8080
    )

    server.listen()
}
